spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tesla?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root2000
  jpa:
    hibernate:
      ddl-auto: update
  #Mail config
  mail:
    host: smtp.gmail.com
    port: 587
    username: smartirosian82@gmail.com
    password: qtetzvpbtaiwaggq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  error:
    whitelabel:
      enabled: false
